/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  luca
 * Created: 14-mag-2016
 */
 
    
    
    
    DROP TABLE SALDO ;
    DROP TABLE CLIENTE_INSERZIONI ;
    DROP TABLE CLIENTE ;
    DROP TABLE VENDITORE ;
    DROP TABLE INSERZIONI ;
    DROP TABLE UTENTE  ;
    
    CREATE TABLE UTENTE (
        ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        NOME VARCHAR(64),
        COGNOME VARCHAR(64),
        USERNAME VARCHAR(64),
        PASSWORD VARCHAR(64),
        SALDO_ID INTEGER,
        TIPO INTEGER
    );
    CREATE TABLE SALDO(
        ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        CONTO DOUBLE,
        UTENTE_ID INTEGER,
        FOREIGN KEY (UTENTE_ID) REFERENCES UTENTE(ID)
    );
    
    CREATE TABLE CLIENTE(
        UTENTE_ID INTEGER PRIMARY KEY,
        FOREIGN KEY (UTENTE_ID) REFERENCES UTENTE(ID)
    );
    CREATE TABLE VENDITORE (
        UTENTE_ID INTEGER PRIMARY KEY,
        FOREIGN KEY (UTENTE_ID) REFERENCES UTENTE(ID)
    );

    CREATE TABLE INSERZIONI (
        ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        TITOLO VARCHAR(64),
        DESCRIZIONE VARCHAR(512),
        PREZZO DOUBLE,
        IMMAGINE BLOB(1024),
        QUANTITA INT,
        CATEGORIA VARCHAR(128),
        VENDITORE_ID INT,
        FOREIGN KEY (VENDITORE_ID) REFERENCES UTENTE(ID)
    );

   CREATE TABLE CLIENTE_INSERZIONI (
        UTENTE_ID INTEGER ,
        INSERZIONE_ID INTEGER ,
        FOREIGN KEY (UTENTE_ID) REFERENCES UTENTE(ID),
        FOREIGN KEY (INSERZIONE_ID) REFERENCES INSERZIONI(ID),
        PRIMARY KEY (UTENTE_ID,INSERZIONE_ID )
    );

INSERT INTO UTENTE (ID,NOME,COGNOME,USERNAME,PASSWORD,TIPO)
VALUES
(DEFAULT,'luca','camboni','lucac','12',1),
(DEFAULT,'davide','spano','admin','admin',1),
(DEFAULT,'carlo','compra','compra','1',2),
(DEFAULT,'ricco','sfondato','sultan','soldi',2);

INSERT INTO SALDO (ID,CONTO,UTENTE_ID)
VALUES
(DEFAULT,0.0,1),
(DEFAULT,0.0,2),
(DEFAULT,123456.78,3),
(DEFAULT,123456789.01,4);

INSERT INTO INSERZIONI (ID,TITOLO,DESCRIZIONE,PREZZO,QUANTITA,CATEGORIA,VENDITORE_ID)
VALUES
(DEFAULT,'Alfa Romeo','usato pari a nuovo come da foto.\n trasporto immediato senza possibilità di reso .',33000.00,3,'Auto',1),
(DEFAULT,'Fiat 500','usato pari a nuovo come da foto.\n trasporto immediato senza possibilità di reso .',17500.00,1,'Auto',2),
(DEFAULT,'Ferrari 488','usato pari a nuovo come da foto.\n trasporto immediato senza possibilità di reso .',220000.00,1,'Auto',2),
(DEFAULT,'Toyota Rav4','usato pari a nuovo come da foto.\n trasporto immediato senza possibilità di reso .',37000.00,1,'Auto',1),
(DEFAULT,'Mercedes classe c','usato pari a nuovo come da foto.\n trasporto immediato senza possibilità di reso .',50000.00,1,'Auto',2),
(DEFAULT,'Bmw r1100','usato pari a nuovo come da foto.\n trasporto immediato senza possibilità di reso .',50000.00,1,'Moto',1),
(DEFAULT,'Ducati 748','usato pari a nuovo come da foto.\n trasporto immediato senza possibilità di reso .',120000.00,1,'Moto',2),
(DEFAULT,'Saramour 46m','usato pari a nuovo come da foto.\n trasporto immediato senza possibilità di reso .',1432765.98,1,'Yatch',2),
(DEFAULT,'Bsc 570','usato pari a nuovo come da foto.\n trasporto immediato senza possibilità di reso .',7000.00,3,'Barche',2),
(DEFAULT,'Chaparral 275','usato pari a nuovo come da foto.\n trasporto immediato senza possibilità di reso .',41600.00,1,'Barche',1);

